{
  "base": "BLACK",
  "colors": {
    "accent": "#ffbd93f9",
    "accentVariant": "#ffbd93f9",
    "secondary": "#ff50fa7b",
    "secondaryVariant": "#ff6272a4",
    "background": "#ff282a36",
    "menus": "#ff44475a",
    "title": "#ff8be9fd",
    "accentVariant2": "#ffff5555",
    "sentMessage": "#ff6272a4",
    "sentReply": "#ffbd93f9",
    "receivedMessage": "#ff44475a",
    "receivedReply": "#ffff79c6",
  }
}
